name: ci
on:
  - push
  - pull_request
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - uses: actions/checkout@v2
      - name: Build
        run: |
          make build
#      - name: Run go/lint
#        run: |
#          export PATH=${PATH}:~/go/bin
#          make go/lint
      - name: Run tests
        run: |
          make test
